# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Osmo < Formula
  desc "Terraform drift absorber — rewrites .tf files to match real-world state"
  homepage "https://github.com/pandey-raghvendra/osmo"
  version "1.4.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pandey-raghvendra/osmo/releases/download/v1.4.0/osmo_1.4.0_darwin_amd64.tar.gz"
      sha256 "ce8160a15201095c74419eaa0dceb0e37b6b53789b6f63392070587bf88b80d8"

      define_method(:install) do
        bin.install "osmo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pandey-raghvendra/osmo/releases/download/v1.4.0/osmo_1.4.0_darwin_arm64.tar.gz"
      sha256 "910dd7d89e0707906b67b1687e6a3db5ef0b54e86ec53c4f6c78498b88135773"

      define_method(:install) do
        bin.install "osmo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pandey-raghvendra/osmo/releases/download/v1.4.0/osmo_1.4.0_linux_amd64.tar.gz"
      sha256 "8ff0bb2302b1d190b16f833fa1ff2367595fb3ab1a7460eef7d5d8bdba5848b1"
      define_method(:install) do
        bin.install "osmo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pandey-raghvendra/osmo/releases/download/v1.4.0/osmo_1.4.0_linux_arm64.tar.gz"
      sha256 "1a3e7498d344186c4b7f5e91ba32aabee4a39ee680c383cbfd951afda0375c9a"
      define_method(:install) do
        bin.install "osmo"
      end
    end
  end

  test do
    system "#{bin}/osmo", "-version"
  end
end
