# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Osmo < Formula
  desc "Terraform drift absorber — rewrites .tf files to match real-world state"
  homepage "https://github.com/pandey-raghvendra/osmo"
  version "1.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pandey-raghvendra/osmo/releases/download/v1.1.0/osmo_1.1.0_darwin_amd64.tar.gz"
      sha256 "d173d9833d09d227f0d6bf4f488bd60038a5c1bc05fc30b4a838d77e1bd69000"

      define_method(:install) do
        bin.install "osmo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pandey-raghvendra/osmo/releases/download/v1.1.0/osmo_1.1.0_darwin_arm64.tar.gz"
      sha256 "7a0937ad5cf8fbd17c53f8491783568ddf8004f8e8646ebb21067ecb15c7a3ff"

      define_method(:install) do
        bin.install "osmo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pandey-raghvendra/osmo/releases/download/v1.1.0/osmo_1.1.0_linux_amd64.tar.gz"
      sha256 "6a7088afe55567ffc6f2952d80864f88f9f2a7cef44a0c9ef1806bece68c7e76"
      define_method(:install) do
        bin.install "osmo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pandey-raghvendra/osmo/releases/download/v1.1.0/osmo_1.1.0_linux_arm64.tar.gz"
      sha256 "e1f4f56af22386bb2b6123c54d84d033a55796cf16887019c0962893354faa36"
      define_method(:install) do
        bin.install "osmo"
      end
    end
  end

  test do
    system "#{bin}/osmo", "-version"
  end
end
